export const weapons = {
  // simple melee
  club: "Club",
  dagger: "Dagger",
  greatclub: "Greatclub",
  handaxe: "Handaxe",
  javelin: "Javelin",
  "light-hammer": "Light hammer",
  mace: "Mace",
  quarterstaff: "Quarterstaff",
  sickle: "Sickle",
  spear: "Spear",
  // simple ranged
  "crossbow-light": "Crossbow, light",
  dart: "Dart",
  shortbow: "Shortbow",
  sling: "Sling",
  // martial melee
  battleaxe: "Battleaxe",
  flail: "Flail",
  glaive: "Glaive",
  greataxe: "Greataxe",
  greatsword: "Greatsword",
  halberd: "Halberd",
  lance: "Lance",
  longsword: "Longsword",
  maul: "Maul",
  morningstar: "Morningstar",
  pike: "Pike",
  rapier: "Rapier",
  scimitar: "Scimitar",
  shortsword: "Shortsword",
  trident: "Trident",
  "war-pick": "War pick",
  warhammer: "Warhammer",
  whip: "Whip",
  // martial ranged
  blowgun: "Blowgun",
  "crossbow-hand": "Crossbow, hand",
  "crossbow-heavy": "Crossbow, heavy",
  longbow: "Longbow",
}
